#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  6 10:09:16 2020

@author: ajv012

Creating GANs for MNIST images
"""

# imports
import torch
from torch import nn, optim
from torch.autograd.variable import Variable 
from torchvision import transforms, datasets

from utils import Logger

print("Done")

